### PR TITLE
Fix tests

### LINKED ISSUE #58: Tests fail on v0.5
The master branch fails on some categories:
```
test cell expressions
  Failure :: (line:272) :: fact was false
    Expression: Parser.parse(ex) |> norm_ast --> Base.parse(ex) |> norm_ast
      Expected: :(Any[i for i = 1:10])
      Occurred: :($(Expr(:typed_comprehension, :Any, :i, :(i = 1:10))))
Out of 9 total facts:
  Verified: 8
  Failed:   1
test cat expressions
  Failure :: (line:272) :: fact was false
    Expression: Parser.parse(ex) |> norm_ast --> Base.parse(ex) |> norm_ast
      Expected: :([i for i = 1:10])
      Occurred: :($(Expr(:comprehension, :i, :(i = 1:10))))
Out of 9 total facts:
  Verified: 8
  Failed:   1
interpolate var in cache block
  Failure :: (line:272) :: fact was false
    Expression: Parser.parse(src) |> norm_ast --> Base.parse(src) |> norm_ast
      Expected: :(try 
    catch $(Expr(:$, :x)) # none, line 3:
    end)
      Occurred: :(try 
    catch $(Expr(:$, :x))
    end)
Out of 1 total fact:
  Failed:   1
```

### PR DESCRIPTION
**Pull request by jakebolewski**
This does not mean that we can parse 0.5 syntax correctly.

Closes #58

### CODE REVIEW

File: src/parser.jl [hunk 1]
```diff
@@ -1460,15 +1470,23 @@ function parse_dict(ps::ParseState, ts::TokenStream, frst, closer, opener)
 end
 
 function parse_comprehension(ps::ParseState, ts::TokenStream, frst, closer, opener, word)
-    itrs = parse_comma_sep_iters(ps, ts, word)
+    if VERSION >= v"0.5-"
```
Comment (tkelman) [inline src/parser.jl]: should be more specific about VERSION comparisons
